<div class="grid gap-5 md:grid-cols-2">
    <div><label class="block text-sm font-medium">Employee ID *</label><input name="employee_id" value="{{ old('employee_id', $employee->employee_id ?? '') }}" required class="mt-1 w-full rounded-lg border px-3 py-2"></div>
    <div><label class="block text-sm font-medium">First Name *</label><input name="first_name" value="{{ old('first_name', $employee->first_name ?? '') }}" required class="mt-1 w-full rounded-lg border px-3 py-2"></div>
    <div><label class="block text-sm font-medium">Middle Name</label><input name="middle_name" value="{{ old('middle_name', $employee->middle_name ?? '') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
    <div><label class="block text-sm font-medium">Last Name *</label><input name="last_name" value="{{ old('last_name', $employee->last_name ?? '') }}" required class="mt-1 w-full rounded-lg border px-3 py-2"></div>
    <div><label class="block text-sm font-medium">Email</label><input type="email" name="email" value="{{ old('email', $employee->email ?? '') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
    <div><label class="block text-sm font-medium">Contact Number</label><input name="contact_number" value="{{ old('contact_number', $employee->contact_number ?? '') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
    <div><label class="block text-sm font-medium">Birthdate</label><input type="date" name="birthdate" value="{{ old('birthdate', isset($employee) && $employee->birthdate ? $employee->birthdate->format('Y-m-d') : '') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
    <div><label class="block text-sm font-medium">Gender</label><select name="gender" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="">Select</option>@foreach(['Male','Female','Other'] as $gender)<option value="{{ $gender }}" @selected(old('gender', $employee->gender ?? '') === $gender)>{{ $gender }}</option>@endforeach</select></div>
    <div><label class="block text-sm font-medium">Department</label><input name="department" value="{{ old('department', $employee->department ?? '') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
    <div><label class="block text-sm font-medium">Position</label><input name="position" value="{{ old('position', $employee->position ?? '') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
    <div><label class="block text-sm font-medium">Date Hired</label><input type="date" name="date_hired" value="{{ old('date_hired', isset($employee) && $employee->date_hired ? $employee->date_hired->format('Y-m-d') : '') }}" class="mt-1 w-full rounded-lg border px-3 py-2"></div>
    <div><label class="block text-sm font-medium">Employment Status *</label><select name="employment_status" required class="mt-1 w-full rounded-lg border px-3 py-2">@foreach(['Active','Inactive','On Leave'] as $status)<option value="{{ $status }}" @selected(old('employment_status', $employee->employment_status ?? 'Active') === $status)>{{ $status }}</option>@endforeach</select></div>
    <div class="md:col-span-2"><label class="block text-sm font-medium">Address</label><textarea name="address" rows="3" class="mt-1 w-full rounded-lg border px-3 py-2">{{ old('address', $employee->address ?? '') }}</textarea></div>
</div>
<div class="mt-6 flex gap-3"><button class="rounded-lg bg-slate-900 px-5 py-2 text-white">{{ $buttonText ?? 'Save Employee' }}</button><a href="{{ route('employees.index') }}" class="rounded-lg border px-5 py-2">Cancel</a></div>
